services:
  spy:
    # Find latest Guardian images in https://github.com/wormhole-foundation/wormhole/pkgs/container/guardiand
    image: ghcr.io/wormhole-foundation/guardiand:v2.23.14
    command:
      - "spy"
      - "--nodeKey"
      - "/node.key"
      - "--spyRPC"
      - "[::]:7072"
      - "--bootstrap"
      - "/dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i"
      - "--network"
      - "/wormhole/testnet/2/1"
      - "--logLevel"
      - "warn"
  price-service:
    # Find latest price service images https://gallery.ecr.aws/pyth-network/xc-server
    image: public.ecr.aws/pyth-network/xc-server:v3.0.8
    environment:
      SPY_SERVICE_HOST: "spy:7072"
      SPY_SERVICE_FILTERS: |
        [
          {
            "chain_id": 1,
            "emitter_address": "f346195ac02f37d60d4db8ffa6ef74cb1be3550047543a4a9ee9acf4d78697b0"
          },
          {
            "chain_id": 26,
            "emitter_address": "a27839d641b07743c0cb5f68c51f8cd31d2c0762bec00dc6fcd25433ef1ab5b6"
          }
        ]
      REST_PORT: "4200"
      PROM_PORT: "8081"
      READINESS_SPY_SYNC_TIME_SECONDS: "5"
      READINESS_NUM_LOADED_SYMBOLS: "280"
      LOG_LEVEL: warning
      WORMHOLE_CLUSTER: testnet
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4200/ready",
        ]
      start_period: 20s
    depends_on:
      - spy
  price-pusher:
    # Use this to build the price pusher from source. A dependency of the pusher docker
    # image is the pyth-crosschain monorepo lerna docker image. Build lerna image
    # using the following command from the repo root:
    # `docker buildx build -f Dockerfile.lerna -t lerna .`
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: .

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v6.0.0
    restart: always
    command:
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://rpc.testnet.mantle.xyz"
      - "--mnemonic-file"
      - "/mnemonic"
      - "--pyth-contract-address"
      - "0xA2aa501b19aff244D90cc15a4Cf739D2725B5729"
      - "--price-service-endpoint"
      - "https://hermes-beta.pyth.network"
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
    depends_on:
      price-service:
        condition: service_healthy
configs:
  mnemonic:
    file: ./mnemonic # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.testnet.yaml # Replace this with the path to the price configuration file
